[package]

name = "ecs"
version = "0.1.0"
authors = ["HeroesGrave <heroesgrave@gmail.com>"]

[dependencies.lazy_static]

git = "https://github.com/Kimundi/lazy-static.rs"

[dependencies.uuid]

git = "https://github.com/rust-lang/uuid"
